In [4]:
import numpy as np

# Sorting Algorithms

## Bubble Sort

In [5]:
def bubble_sort(arr):
    n=len(arr)
    for i in range(n):
        isSwapped = False
        for j in range(n-1-i):
            if arr[j]>arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                isSwapped = True
        if not isSwapped: break
    return arr

print(bubble_sort([2]))
print(bubble_sort([2,3,5,1,7,4]))
print(bubble_sort(np.random.randint(low=10,high=100,size=10)))


[2]
[1, 2, 3, 4, 5, 7]
[10 10 41 41 42 50 63 64 80 90]


## Insertion Sort

In [6]:
def insertion_sort(arr):
    n = len(arr)
    for i in range(1, n):
        key = arr[i]
        j = i-1
        while j>=0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key
    return arr

print(insertion_sort([]))
print(insertion_sort([3]))
print(insertion_sort([5, 3, 4, 1, 2]))
print(insertion_sort(np.random.randint(low=10,high=100,size=10)))

[]
[3]
[1, 2, 3, 4, 5]
[11 18 23 30 42 70 83 90 95 98]


## Selection Sort

In [7]:
def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_val_i = i
        for j in range(i+1,n):
            if arr[j] < arr[min_val_i]:
                min_val_i = j
        arr[i], arr[min_val_i] = arr[min_val_i], arr[i]
    return arr

print(selection_sort([]))
print(selection_sort([3]))
print(selection_sort([2,3,5,1,7,4]))
print(selection_sort(np.random.randint(low=10,high=100,size=10)))

[]
[3]
[1, 2, 3, 4, 5, 7]
[22 23 28 29 35 51 52 66 81 87]
