# 1. NumPy Practical Interview Questions
## Basic Level
##### 1. Create a 1D NumPy array of numbers from 1 to 20.


In [ ]:
import numpy as np

arr=np.arange(2,22,1)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


##### 2. Create a 3x3 identity matrix

In [ ]:
arr=np.eye(3, 3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 3. Generate a 4x4 array of random integers between 10 and 50.

In [ ]:
arr=np.random.randint(10,51, size=(4, 4)) # np.random.uniform(10, 51, size=(4, 4)) for float number
print(arr)

[[40 19 33 33]
 [10 25 45 21]
 [38 14 22 41]
 [44 18 46 48]]


##### 4. Create an array of even numbers from 2 to 40.

In [ ]:
# First Method: When you know the step size
arr=np.arange(2, 41, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
# Second Method: When you know how many values you want
arr=np.linspace(4, 40, 10, dtype=int) # By default, they will return float number.
print(arr)

[ 4  8 12 16 20 24 28 32 36 40]


##### 5. Convert a 1D array into a 2D array with 4 rows.

In [ ]:
arr=np.arange(1, 13)
mod_arr=arr.reshape(4, 3)#You can set 3 as -1, so numpy will calculate -1 dimension automatically(E.g=arr.reshape(3,-1))
print(mod_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##### 6. Find the maximum, minimum, and mean of a NumPy array.

In [ ]:
arr=np.random.randint(1, 100, size=(10))
print(arr)
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))

[84 22 45 24 79 96 64 94 77 22]
22
96
60.7


In [ ]:
# If it's a 2D Array
arr=np.random.randint(1, 100, size=(4, 3))
print(arr)
print("Min: ", np.min(arr, axis=0))
print("Max: ", np.max(arr, axis=0))
print("Mean: ", np.mean(arr, axis=0))

[[84 25 74]
 [81 84 34]
 [68 15 20]
 [39 28 92]]
Min:  [39 15 20]
Max:  [84 84 92]
Mean:  [68. 38. 55.]


##### 7. Reverse a NumPy array without using loops.

In [ ]:
arr=np.random.randint(1, 101, size=(10))
print(arr)
print(arr[::-1])

[77 76 35 18 82  8 72 33  9 95]
[95  9 33 72  8 82 18 35 76 77]


In [ ]:
# Reverse a 2D array along rows
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[:, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


##### 8. Replace all odd numbers in an array with -1.

In [ ]:
arr=np.array([3,6,3,26,7,8,8,43,756,432,94])

arr[arr % 2 == 1] = -1
print(arr)

[ -1   6  -1  26  -1   8   8  -1 756 432  94]


In [ ]:
# For 2D Array
arr=np.random.randint(1, 101, size=(3, 3))
print(arr)
arr[arr % 2 == 1] = -1
print(arr)

[[  2  73  22]
 [ 28  52  61]
 [ 36 100   5]]
[[  2  -1  22]
 [ 28  52  -1]
 [ 36 100  -1]]


In [ ]:
# Alternate Example using Where()
arr=np.random.randint(1, 101, size=(3, 3))
mod_arr=np.where(arr % 2 == 1, -1, arr)
print(arr)
print(mod_arr)

[[96 92 97]
 [15 88 34]
 [13 24  3]]
[[96 92 -1]
 [-1 88 34]
 [-1 24 -1]]


In [ ]:
# Targetting First Row only
arr=np.random.randint(1, 101, size=(3, 3))
print(arr)
arr[0,arr[0]%2==1]=-1#Select the first row,and in that row,target all elements that are odd,then replace those odd numbers with -1
print(arr)

[[82 85 45]
 [86  7 63]
 [45 30 64]]
[[82 -1 -1]
 [86  7 63]
 [45 30 64]]


In [ ]:
# Targetting First Column only
arr=np.random.randint(1, 101, size=(3, 3))
print(arr)
arr[arr[:, 0] % 2 ==1, 0]=-1 # Select all rows where the first column is odd,and in those rows, target column 0.
print(arr)

[[71 60 47]
 [18 46  2]
 [ 3 91 50]]
[[-1 60 47]
 [18 46  2]
 [-1 91 50]]


##### 9. Extract all values greater than a given number from an array.

In [ ]:
# 1D Array
num=50
arr=np.random.randint(1, 101, size=(10), dtype=int)
result= arr[arr > num]
print(arr)
print(result)

[13 45  8 38 67 47 97 45 20 12]
[67 97]


In [ ]:
# 2D Array
num=50
arr=np.random.randint(1, 101, size=(3, 3), dtype=int)
result=arr[arr > num]
print(arr)
print(result)

[[80 82 28]
 [ 4 58 20]
 [68 25 56]]
[80 82 58 68 56]


In [ ]:
# Using Where() Method
num=50
arr=np.random.randint(1, 101, size=(3, 3), dtype=int)
print(arr)
indices=np.where(arr > num)
print("Positions: ", list(zip(indices[0], indices[1])))
print("Values: ", arr[indices])

[[91 56 22]
 [77 12 55]
 [55 10 70]]
Positions:  [(np.int64(0), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(2))]
Values:  [91 56 77 55 55 70]


###### 10. Flatten a 2D array into a 1D array

In [ ]:
# Using Flatten Method
arr=np.random.randint(1, 101, size=(3, 3), dtype=int)
print(arr)
result=arr.flatten() # Creates a "Copy" of an Array
print(result)

[[31 37 44]
 [53 58 88]
 [14 18 68]]
[31 37 44 53 58 88 14 18 68]


In [ ]:
# Using Reshape Method
arr=np.random.randint(1, 101, size=(3, 3), dtype=int)
print(arr)
result=arr.reshape(-1) # Creates a "View" of an Array
print(result)

[[21 61  8]
 [54 38 88]
 [ 8 33 28]]
[21 61  8 54 38 88  8 33 28]


In [ ]:
# Using Ravel Method
arr=np.random.randint(1, 101, size=(3, 3), dtype=int)
print(arr)
result=arr.ravel()
print(result)

[[89 25 54]
 [17 95 35]
 [ 8 56  5]]
[89 25 54 17 95 35  8 56  5]


## Intermediate Level
###### 11. Create a 5x5 matrix and set its diagonal elements to 1 and the rest to 0.

In [ ]:
# Using Zeroes and Fill_diagonal function
arr=np.zeros((5, 5), dtype=int)
np.fill_diagonal(arr, 1)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# Using Eye Function
arr=np.eye(6, k=1, dtype=int) # k argument tells numpy how far to shift the diagonal, positive values shift it upward (right),negative values shift it downward (left)
print(arr)

[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


###### 12. Generate a 3x3 array with values ranging from 10 to 18

In [ ]:
# Using Arange function and reshape method
arr=np.arange(10, 19).reshape(3, 3)
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
# Using Linspace Function
arr=np.linspace(10, 18, 9, dtype=int).reshape(3,3)
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


###### 13. Normalize an array so that all values fall between 0 and 1.

In [ ]:
arr=np.random.randint(10, 100, size=10, dtype=int)
normalized= (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)

[0.25862069 0.82758621 0.13793103 0.13793103 0.34482759 0.89655172
 0.06896552 0.68965517 1.         0.        ]


###### 14. Multiply two matrices using NumPy's dot product

In [ ]:
arr1=np.random.randint(1, 10, size=(2,3))
arr2=np.random.randint(1, 10, size=(3,2))
print(arr1)
print(arr2)
arr3=np.dot(arr1, arr2) # OR  result = A @ B   OR   result = np.matmul(A, B)
print(arr3)

[[7 9 7]
 [6 9 6]]
[[5 3]
 [9 1]
 [9 5]]
[[179  65]
 [165  57]]


###### 15. Compute the sum of each column and each row in a 2D array.

In [ ]:
arr=np.random.randint(1, 20, dtype=int, size=(3, 3))
print(arr)
row_sum=np.sum(arr, axis=1) # If no axis is specified, It will calculate the sum of all arrays
col_sum=np.sum(arr, axis=0)
print(row_sum)
print(col_sum)

[[12 13 19]
 [14  6  9]
 [ 9 17  4]]
[44 29 30]
[35 36 32]


###### 16. Stack two arrays vertically and horizontally

In [ ]:
# 2D Arrays
arr1=np.random.randint(1, 20, size=(2, 3))
arr2=np.random.randint(1, 20, size=(2, 3))
print(arr1)
print(arr2)

v_stacked=np.vstack((arr1, arr2)) # No. of Columns must match, It increases the No. of Rows
print(v_stacked)
h_stacked=np.hstack((arr1, arr2)) # No. of Rows must match, It increases the No. of Columns
print(h_stacked)

[[11 17 19]
 [17  7  1]]
[[ 1 19 16]
 [ 1 18  6]]
[[11 17 19]
 [17  7  1]
 [ 1 19 16]
 [ 1 18  6]]
[[11 17 19  1 19 16]
 [17  7  1  1 18  6]]


In [ ]:
# Using np.concatenate()
# 2D Arrays
arr1=np.random.randint(1, 20, size=(2, 3))
arr2=np.random.randint(1, 20, size=(2, 3))
print(arr1)
print(arr2)
v_stack=np.concatenate((arr1, arr2), axis=0)
h_stack=np.concatenate((arr1, arr2), axis=1)
print(v_stack)
print(h_stack)

[[ 6  3  5]
 [13  9 18]]
[[ 8 14  3]
 [14 18 14]]
[[ 6  3  5]
 [13  9 18]
 [ 8 14  3]
 [14 18 14]]
[[ 6  3  5  8 14  3]
 [13  9 18 14 18 14]]


###### 17. Create two arrays and perform element-wise addition, subtraction, and division

In [ ]:
arr1=np.random.randint(1, 20, size=(2, 3))
arr2=np.random.randint(1, 20, size=(2, 3))
print(arr1)
print(arr2)
print("Adding: \n",np.add(arr1, arr2)) # arr1 + arr2
print("Subtracting: \n", np.subtract(arr1, arr2)) # arr1 - arr2
print("Dividing: \n", np.divide(arr1, arr2)) # arr1 / arr2

[[ 6  7  5]
 [12  3 16]]
[[ 9 17  2]
 [16 13 12]]
Adding: 
 [[15 24  7]
 [28 16 28]]
Subtracting: 
 [[ -3 -10   3]
 [ -4 -10   4]]
Dividing: 
 [[0.66666667 0.41176471 2.5       ]
 [0.75       0.23076923 1.33333333]]
[[ 54 119  10]
 [192  39 192]]


###### 18. Use broadcasting to add a 1D array to each row of a 2D array.

In [ ]:
# Row Wise
two_d = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]])
one_d = np.array([10, 20, 30])

print(one_d + two_d)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
# Column Wise
two_d = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]])
one_d = np.array([10, 20, 30])

one_d = one_d.reshape(3, 1)
print(one_d + two_d)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


###### 19. Generate a 3x3 matrix and find its determinant.

In [ ]:
arr=np.random.randint(1, 20, size=(3, 3))
print(arr)
determinant=np.linalg.det(arr)
print("Determinant: ", round(determinant, 2))

[[10 14 19]
 [10 11  8]
 [15 15  3]]
Determinant:  105.0


###### 20. Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [ ]:
arr=np.array([[3, 9], [6, 12]])
eigen_value, eigen_vector=np.linalg.eig(arr)
print("Eigen Values: ", eigen_value)
print("Eigen Vectors: ", eigen_vector)

Eigen Values:  [-1.11684397 16.11684397]
Eigen Vectors:  [[-0.90937671 -0.56576746]
 [ 0.41597356 -0.82456484]]


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9,0,1,2])

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [ ]:
arr1.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2]])

In [ ]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [ ]:
arr=arr1.reshape(2,3,2)
arr

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 0],
        [1, 2]]])

In [ ]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [ ]:
arr[1,1,1]=30
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 30],
        [ 1,  2]]])

In [ ]:
arr2=np.ones((10,2))
arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arr3=np.arange(1.2,50,3)
arr3

array([ 1.2,  4.2,  7.2, 10.2, 13.2, 16.2, 19.2, 22.2, 25.2, 28.2, 31.2,
       34.2, 37.2, 40.2, 43.2, 46.2, 49.2])

In [ ]:
arr4=np.linspace(1,10,3)
arr4

array([ 1. ,  5.5, 10. ])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

arr1 = np.array([True, False, True, False, True])

result = arr[arr1]

print(result)

[10 30 50]


In [ ]:
arr1=np.array([
    [1,2,3],
    [4,5,6]
])
arr2=np.array([
    [7,8],
    [1,2],
    [1,2]
])
arrnew1=arr1.flatten()
arrnew2=arr2.flatten()
arrnew1
arrnew2
arr=np.dot(arrnew1,arrnew2)
arr

np.int64(51)

In [ ]:
arr=np.transpose(arr1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([[10],[20]])

A + B

array([[11, 12, 13],
       [24, 25, 26]])

In [ ]:
arr5=[1,2,3,4,5,6,7]
np.random.choice(arr5,size=3,p=[0.1,0.1,0.15,0.15,0.1,0.2,0.2])

array([6, 4, 6])

In [ ]:
arr=np.random.permutation(arr5)
arr

array([1, 4, 7, 6, 5, 2, 3])

In [ ]:
np.random.shuffle(arr5)
arr5

[7, 2, 3, 1, 6, 4, 5]